.github/workflows/edge.yml
.github/workflows/pr_ci.yml
.github/workflows/stable.yml

Fixes kagemomiji/airsonic-advanced#1
Signed-off-by: Y.Tory <kagemomiji.dev@gmail.com>

Support CI action to kagemomiji/airsonic-advance

---

pom.xml

Fixes kagemomiji/airsonic-advanced#10

Update pom.xml for this repo

---

.github/workflows/edge.yml
.github/workflows/pr_ci.yml
.github/workflows/stable.yml
airsonic-main/pom.xml
airsonic-main/src/main/java/org/airsonic/player/domain/UserCredential.java
airsonic-main/src/test/java/org/airsonic/player/dao/InternetRadioDaoTestCase.java
airsonic-main/src/test/java/org/airsonic/player/dao/MusicFolderDaoTestCase.java
airsonic-main/src/test/java/org/airsonic/player/dao/PlayerDaoTestCase.java
airsonic-main/src/test/java/org/airsonic/player/dao/PodcastDaoTestCase.java
airsonic-main/src/test/java/org/airsonic/player/domain/PlayQueueTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/InternetRadioServiceTest.java
airsonic-main/src/test/java/org/airsonic/player/service/MediaScannerServiceTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/search/IndexManagerTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/search/QueryFactoryTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/search/SearchServiceSpecialGenreTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/search/SearchServiceSpecialPathTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/search/SearchServiceStartWithStopwardsTestCase.java
airsonic-main/src/test/java/org/airsonic/player/util/MusicFolderTestData.java
install/docker/Dockerfile
install/docker/pom.xml
pom.xml
repo/com/github/muff1nman/chameleon/chameleon-parent/2.0.0-RELEASE/chameleon-parent-2.0.0-RELEASE.pom

Fixes kagemomiji/airsonic-advanced#9

[fix] #9 fixed ci build edge faiure

---

.github/workflows/edge.yml
.github/workflows/pr_ci.yml

Fixes kagemomiji/airsonic-advanced#13

Ignore .github directory update by ci actions

---

.github/dependabot.yml

Fixes kagemomiji/airsonic-advanced#14

Add update dependabot for CI

---

.github/workflows/pr_ci.yml

Fixes kagemomiji/airsonic-advanced#13

[update] added self to exception of ignore in pr_ci.yml

---

README.md

Fixes kagemomiji/airsonic-advanced#8

Issue8-replace-repository-name-in-README

---

airsonic-main/pom.xml

Fixes kagemomiji/airsonic-advanced#27

Issue27-bump-up-jdom

---

.github/workflows/trivy_scan.yml

Fixes kagemomiji/airsonic-advanced#30

Add Trivy scan for  check vulnerability

---

.github/workflows/trivy_scan.yml

Fixes kagemomiji/airsonic-advanced#30

add push main baranches trigger

---

airsonic-main/src/main/java/org/airsonic/player/security/GlobalSecurityConfig.java
airsonic-main/src/main/java/org/airsonic/player/service/upnp/DispatchingContentDirectory.java
airsonic-main/src/main/java/org/airsonic/player/spring/WebsocketConfiguration.java
airsonic-main/src/main/resources/application.properties
airsonic-main/src/test/java/org/airsonic/player/service/PlaylistServiceTestExport.java
airsonic-main/src/test/resources/application.properties
pom.xml

Fixes kagemomiji/airsonic-advanced#33

Bump up org.springframework.security:spring-security-core version

---

airsonic-main/pom.xml
pom.xml

Fixes kagemomiji/airsonic-advanced#35

Bump up apache-commons-text

---

pom.xml

Fixes kagemomiji/airsonic-advanced#37

Bump up Apache CXF

---

airsonic-main/pom.xml
pom.xml

Fixes kagemomiji/airsonic-advanced#38

Bump up org.liquibase:liquibase-core

---

airsonic-main/pom.xml
integration-test/pom.xml
pom.xml

Fixes kagemomiji/airsonic-advanced#41

Bump up snakeyml

---

airsonic-main/pom.xml
airsonic-sonos-api/pom.xml
install/docker/pom.xml
integration-test/pom.xml
pom.xml
subsonic-rest-api/pom.xml

Fixes kagemomiji/airsonic-advanced#45

Bump up version to 11.0.1

---

.github/workflows/pr_build_docker.yml

Fixes kagemomiji/airsonic-advanced#49

Add build docker image on pr for test

---

integration-test/src/test/java/org/airsonic/test/Scanner.java

Fixes kagemomiji/airsonic-advanced#55

change ObjectMapper to JsonMapper.builder to treat deprecated

---

airsonic-main/src/test/java/org/airsonic/player/dao/MusicFolderDaoTestCase.java
airsonic-main/src/test/java/org/airsonic/player/dao/PlayerDaoTestCase.java
airsonic-main/src/test/java/org/airsonic/player/dao/UserDaoTestCase.java
integration-test/src/test/java/org/airsonic/test/PingIT.java

Fixes kagemomiji/airsonic-advanced#57

#57 treat deprecated assertion method in tests

---

airsonic-main/src/main/java/org/airsonic/player/dao/AbstractDao.java

Fixes kagemomiji/airsonic-advanced#60

Treat deprecated jdbcTemplate methods

---

airsonic-main/src/test/java/org/airsonic/player/service/PlaylistServiceTestExport.java

Fixes kagemomiji/airsonic-advanced#61

Treat stream deprecated methods

---

airsonic-main/src/main/java/org/airsonic/player/filter/ParameterDecodingFilter.java
airsonic-main/src/main/java/org/airsonic/player/filter/ResponseHeaderFilter.java
airsonic-main/src/main/java/org/airsonic/player/monitor/MetricsManager.java
airsonic-main/src/test/java/org/airsonic/player/service/PlaylistServiceTestImport.java

[fix] #66 treat raw type warning

---

airsonic-main/src/main/java/org/airsonic/player/service/JukeboxService.java
airsonic-main/src/main/java/org/airsonic/player/service/sonos/SonosHelper.java

Fixes kagemomiji/airsonic-advanced#71

Treat warnings of switch statement with enum

---

airsonic-main/src/main/java/org/airsonic/player/controller/EditTagsController.java
airsonic-main/src/main/java/org/airsonic/player/service/JWTSecurityService.java
airsonic-main/src/main/java/org/airsonic/player/service/StatusService.java
airsonic-main/src/main/java/org/airsonic/player/service/metadata/FFmpegParser.java
airsonic-main/src/main/java/org/airsonic/player/service/scrobbler/ListenBrainzScrobbler.java
airsonic-main/src/main/java/org/airsonic/player/service/upnp/RootUpnpProcessor.java
airsonic-main/src/test/java/org/airsonic/player/service/InternetRadioServiceTest.java

Fixes kagemomiji/airsonic-advanced#73

Remove unused variable

---

airsonic-main/pom.xml
airsonic-sonos-api/pom.xml
install/docker/pom.xml
integration-test/pom.xml
pom.xml
subsonic-rest-api/pom.xml

Fixes kagemomiji/airsonic-advanced#75

Bump up to 11.0.2

---

pom.xml

Fixes kagemomiji/airsonic-advanced#77

Bump up springboot version to 2.7.x

---

.github/workflows/pr_build_docker.yml

Fixes kagemomiji/airsonic-advanced#84

change docker build on pr trigger to pull_request_target and labeled

---

.github/workflows/pr_build_docker.yml

Fixes kagemomiji/airsonic-advanced#88

Issue88-fix-ci-on-pr

---

airsonic-main/pom.xml

Fixes kagemomiji/airsonic-advanced#90

[fix] #90 replace jdbc mysql connector 

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Fixes kagemomiji/airsonic-advanced#99

Add configuration and database information form to Bug issue template

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/documentation.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/repository_maintenance.yaml
.github/PULL_REQUEST_TEMPLATE.md
README.md

[update] #101 maintain repository

---

.github/workflows/pr_ci.yml
.github/workflows/stable.yml

Fixes kagemomiji/airsonic-advanced#104

[Chore]: Bump up actions/checkout to v3

---

.github/workflows/codeql.yml
.github/workflows/edge.yml

[Chore]: #119 change CI from upstream for this repository

---

.github/workflows/codeql.yml
.github/workflows/edge.yml

[Chore]: #121 remove if statements from edge.yml

---

airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
airsonic-main/src/main/java/org/airsonic/player/service/metadata/MetaDataParserFactory.java
airsonic-main/src/test/java/org/airsonic/player/service/MediaFileServiceTest.java
airsonic-main/src/test/resources/MEDIAS/invalidCue/airsonic-test.cue
pom.xml

Fixes kagemomiji/airsonic-advanced#126

[fix] bug of  Untreated IndexOutOfBoundsException stop IndexWriter

---

.mvn/maven.config

Fixes kagemomiji/airsonic-advanced#133

[chore] fix failure of build with maven in GitHub Action

---

airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java

Fixes #130 
2 Fixes included
- fix misconfiguration of the cache key of getMediaFile
- fix bug of calculate flag to load media file from disk

[fix] #130 fix scan file performance problem

---

airsonic-main/src/main/webapp/WEB-INF/jsp/search.jsp

Fixes kagemomiji/airsonic-advanced#137
remove unnecessary parameter `directory` from the rendering of  search results about `artist` and `album`

fix bug of Search gives error 'Whitelabel Error Page'

---

.github/ISSUE_TEMPLATE/bug_report.yaml
CHANGELOG.md
airsonic-main/pom.xml
airsonic-sonos-api/pom.xml
install/docker/pom.xml
integration-test/pom.xml
pom.xml
subsonic-rest-api/pom.xml

Fixes kagemomiji/airsonic-advanced#80

release 11.1.0

---

.github/workflows/pr_build_docker.yml
.github/workflows/pr_build_docker_from_fork.yml

Fixes kagemomiji/airsonic-advanced#142

#142 support build docker image at dependabot PR

---

.github/workflows/pr_build_docker_from_fork.yml

Fixes kagemomiji/airsonic-advanced#169

#169 fix pr_build_docker_from_fork.yml syntax error

---

airsonic-main/src/main/java/org/airsonic/player/ajax/MediaFileWSController.java
airsonic-main/src/main/java/org/airsonic/player/controller/NowPlayingController.java
airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java

#131 add null check before isRoot method call

---

airsonic-main/src/main/webapp/script/DataTables/Buttons-2.3.6/js/buttons.colVis.js
airsonic-main/src/main/webapp/script/DataTables/DataTables-1.13.4/js/jquery.dataTables.js

#161 fix incomplete sanitizing

---

CHANGELOG.md
README.md

#176 add changelog for 11.1.1

---

.github/ISSUE_TEMPLATE/bug_report.yaml
airsonic-main/pom.xml
airsonic-main/src/main/java/org/airsonic/player/controller/StreamController.java
airsonic-main/src/main/java/org/airsonic/player/io/ShoutCastOutputStream.java
airsonic-sonos-api/pom.xml
install/docker/pom.xml
integration-test/pom.xml
pom.xml
subsonic-rest-api/pom.xml

Fix #87
Add sleep to SHOUTcast streaming process.
Bump up to 11.1.2-SNAPSHOT
Change encoding of the track title for SHOUTcast to UTF-8
Tested by foobar2000/Winamp/AIMP

#87 fix bad behaviour with external player

---

airsonic-main/src/main/webapp/WEB-INF/jsp/externalPlayer.jsp
airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp
airsonic-main/src/main/webapp/WEB-INF/jsp/videoPlayer.jsp

#183 add iconSprite options for custom context path

---

airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
airsonic-main/src/main/java/org/airsonic/player/service/MediaScannerService.java

#187 fix library byte size problem

---

airsonic-main/src/main/java/org/airsonic/player/controller/UploadController.java
airsonic-main/src/main/java/org/airsonic/player/upload/UploadListener.java

#197 fix numeric cast of long to int

---

airsonic-main/src/main/java/org/airsonic/player/controller/AvatarUploadController.java
airsonic-main/src/main/java/org/airsonic/player/controller/StreamController.java
airsonic-main/src/main/java/org/airsonic/player/controller/UploadController.java
airsonic-main/src/main/java/org/airsonic/player/upload/MonitoredMultipartFile.java

#201 Fix uncontrolled data path from user provided parameter

---

airsonic-main/src/main/java/org/airsonic/player/service/StatusService.java

#181 fix duplication of recently played list

---

README.md
docs/troubleshooting.md

#195 add troubleshooting for cue sheet tracks do not end

---

CHANGELOG.md

#206 add ChangeLog about 11.1.2

---

.github/ISSUE_TEMPLATE/bug_report.yaml
airsonic-main/pom.xml
airsonic-main/src/main/webapp/WEB-INF/jsp/playlists.jsp
airsonic-sonos-api/pom.xml
install/docker/pom.xml
integration-test/pom.xml
pom.xml
subsonic-rest-api/pom.xml

#203 fix playlist length view

---

airsonic-main/pom.xml

#231 bump up liquibase version to 4.22.0

---

airsonic-main/src/main/webapp/WEB-INF/jsp/musicFolderSettings.jsp

#243 fix bug of clearFullScanSettingAfterScan not cleared after scan

---

airsonic-main/src/main/java/org/airsonic/player/config/ThreadPoolConfig.java
airsonic-main/src/main/java/org/airsonic/player/service/PlayQueueService.java
airsonic-main/src/main/java/org/airsonic/player/service/PodcastService.java
airsonic-main/src/main/java/org/airsonic/player/service/websocket/AsyncWebSocketClient.java
airsonic-main/src/test/java/org/airsonic/player/service/PlayQueueServiceTest.java
airsonic-main/src/test/java/org/airsonic/player/service/PodcastServiceTestCase.java

Fix #245 
- Use mothods with `@Async` annotation for broadcast to Websocket in PlayQueueService
- Create thread pool for broadcast to Websocket

#245 Replace runAsync to methods with Async annotation in PlayQueueService 

---

airsonic-main/src/main/java/org/airsonic/player/service/PlayQueueService.java
airsonic-main/src/main/java/org/airsonic/player/service/jukebox/AudioPlayer.java
docs/README.md
docs/media/jukebox.md

#248 fix VerifyError problem by enum with switch statement at jukebox audioplayer

---

airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
airsonic-main/src/test/java/org/airsonic/player/service/MediaFileServiceTest.java
airsonic-main/src/test/java/org/airsonic/player/service/MediaScannerServiceTestCase.java

#255 refactored cue indexing at media library scan

---

airsonic-main/pom.xml
pom.xml

Fix #257 
SpringBoot version to 2.7.14
bcprov-jdk to 1.76
mysql-connector-j to 8.0.33

#257 bump up dependent libraries for vulns

---

README.md
install/compose/docker-compose.hsqldb.yaml
install/compose/docker-compose.postgres.yaml

Added Docker Compose files and docs

Docker Compose examples

---

airsonic-main/src/main/java/org/airsonic/player/domain/entity/UserRating.java
airsonic-main/src/main/java/org/airsonic/player/domain/entity/UserRatingKey.java
airsonic-main/src/main/java/org/airsonic/player/repository/UserRatingRepository.java
airsonic-main/src/main/java/org/airsonic/player/service/RatingService.java
airsonic-main/src/test/java/org/airsonic/player/repository/UserRatingRepositoryTest.java
airsonic-main/src/test/java/org/airsonic/player/service/RatingServiceTest.java
pom.xml

#212 
Implement UserRatingRepository to replace RatingDao.

#212 implement UserRatingRepository

---

airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
airsonic-main/src/main/java/org/airsonic/player/controller/UserSettingsController.java
airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java
airsonic-main/src/main/java/org/airsonic/player/service/PlaylistService.java
airsonic-main/src/main/java/org/airsonic/player/service/SecurityService.java
airsonic-main/src/main/java/org/airsonic/player/service/UserService.java
airsonic-main/src/main/java/org/airsonic/player/service/UserServiceImpl.java
airsonic-main/src/test/java/org/airsonic/player/service/PlaylistServiceTestExport.java
airsonic-main/src/test/java/org/airsonic/player/service/PlaylistServiceTestImport.java

Closes #253 
I decided to stick with
> If I create new full permissions user (say, root_admin) and try to delete old default one
> Make a user with admin priv, and delete the admin

Changed user deletion logic

---

airsonic-main/src/main/java/org/airsonic/player/domain/MediaFile.java
airsonic-main/src/main/java/org/airsonic/player/service/search/SearchServiceUtilities.java

#284 Fix transactional error from SearchUtilities while scanning 

---

airsonic-main/src/test/java/org/airsonic/player/repository/AlbumRepositoryTest.java
airsonic-main/src/test/java/org/airsonic/player/repository/ArtistRepositoryTest.java
pom.xml

#291 bump up spring-boot-starter-parent to 2.7.16

---

airsonic-main/src/main/java/org/airsonic/player/service/VersionService.java

#295 increase entities from release api page

---

airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java

#293 add musicFolderId to getArtists endpoint

---

airsonic-main/src/main/java/org/airsonic/player/dao/MediaFileDao.java
airsonic-main/src/main/java/org/airsonic/player/service/PlayerService.java

#306 change timing of deleting old player from post construct to application ready

---

airsonic-main/src/main/resources/liquibase/11.1/changelog.xml
airsonic-main/src/main/resources/liquibase/11.1/remove-genre-name-duplication.xml

#321 add remove duplication of name in genre

---

airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
airsonic-main/src/main/java/org/airsonic/player/service/PodcastPersistenceService.java
airsonic-main/src/main/java/org/airsonic/player/service/podcast/PodcastDownloadClient.java
airsonic-main/src/main/java/org/airsonic/player/util/FileUtil.java
airsonic-main/src/main/webapp/WEB-INF/jsp/podcastChannels.jsp
airsonic-main/src/test/java/org/airsonic/player/service/PodcastPersistenceServiceTestCase.java
airsonic-main/src/test/java/org/airsonic/player/service/podcast/PodcastDownloadClientIntegrationTest.java

#324 Fix podcasts issues

---

airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
airsonic-main/src/main/java/org/airsonic/player/repository/ArtistRepository.java
airsonic-main/src/main/java/org/airsonic/player/repository/MediaFileRepository.java
airsonic-main/src/main/java/org/airsonic/player/service/AlbumService.java
airsonic-main/src/main/java/org/airsonic/player/service/ArtistService.java
airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java

#301 Change logic of search3 API to improve performance

---

airsonic-main/pom.xml
pom.xml

#340 Update logback and Spring Boot version

---

airsonic-main/src/main/java/org/airsonic/player/repository/AlbumRepository.java
airsonic-main/src/main/java/org/airsonic/player/repository/CoverArtRepository.java
airsonic-main/src/main/java/org/airsonic/player/repository/CustomAvatarRepository.java
airsonic-main/src/main/java/org/airsonic/player/repository/MediaFileRepository.java
airsonic-main/src/main/java/org/airsonic/player/repository/PlayerRepository.java
airsonic-main/src/main/java/org/airsonic/player/repository/StarredMediaFileRepository.java

#345 Add Transactional annotation to delete methods of repositories

---

airsonic-main/src/main/java/org/airsonic/player/service/SecurityService.java

#351 Fix cache problem in SecurityService

---

airsonic-main/src/main/java/org/airsonic/player/service/PlayerService.java

#353 Fix code scanning alert about cookies

---

airsonic-main/src/main/java/org/airsonic/player/command/MusicFolderSettingsCommand.java
airsonic-main/src/main/java/org/airsonic/player/controller/CaptionsController.java

#357 fix uncontrolled security alert

---

airsonic-main/src/main/java/org/airsonic/player/controller/CaptionsController.java

#357 fix uncontrolled command alert

---

.github/workflows/pr_build_docker.yml
.github/workflows/pr_build_docker_from_fork.yml

#361 Update build process to include Docker image creation and artifact upload

---

airsonic-main/src/main/java/org/airsonic/player/repository/AlbumRepository.java
airsonic-main/src/main/java/org/airsonic/player/repository/ArtistRepository.java
airsonic-main/src/main/java/org/airsonic/player/service/AlbumService.java
airsonic-main/src/main/java/org/airsonic/player/service/ArtistService.java

#363 check existence before marknonpresent

---

airsonic-main/src/main/java/org/airsonic/player/controller/StreamController.java
airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java

#271 Force ignoring icecast request from Tempo client

---

airsonic-main/pom.xml
airsonic-main/src/main/java/org/airsonic/player/service/PlaylistService.java
airsonic-main/src/test/java/org/airsonic/player/repository/AlbumRepositoryTest.java
airsonic-main/src/test/java/org/airsonic/player/repository/ArtistRepositoryTest.java
airsonic-sonos-api/pom.xml
install/docker/pom.xml
integration-test/pom.xml
pom.xml
subsonic-rest-api/pom.xml

#368 Fix updating playlist with null name failed via API 

---

airsonic-main/src/main/resources/templates/right.html

#381 recover NowPlaying View at right column

---

airsonic-main/src/main/resources/templates/podcastChannels.html

#378 fix podcastsChannels rendering error if custom playlist page size is configured

---

airsonic-main/src/main/java/org/airsonic/player/service/PodcastPersistenceService.java
airsonic-main/src/main/java/org/airsonic/player/util/NetworkUtil.java
airsonic-main/src/main/resources/templates/podcastChannels.html

#388 fix deleting null podcast channel

---

airsonic-main/src/main/java/org/airsonic/player/repository/AlbumRepository.java
airsonic-main/src/main/java/org/airsonic/player/service/AlbumService.java

#387 fixed issue of getAlbumList2 failed by patrameter value mismatch

---

airsonic-main/src/main/java/org/airsonic/player/service/AlbumService.java
airsonic-main/src/main/java/org/airsonic/player/service/ArtistService.java

#392 fix coverart not showing problem

---

.github/ISSUE_TEMPLATE/bug_report.yaml

#405 update bug issue template for 11.1.4-SNAPSHOT

---

airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
airsonic-main/src/main/java/org/airsonic/player/service/PlaylistService.java
airsonic-main/src/main/java/org/airsonic/player/spring/CacheConfiguration.java

#407 add *.view endpoints to RestfulAPI

---

.github/workflows/pr_ci.yml

kagemomiji/airsonic-advanced#411 add jdk21 tests to CI

---

airsonic-main/src/main/java/org/airsonic/player/controller/DownloadController.java

#415 fix typo at DownloadController

---

.github/dependabot.yml

#418 Add dependabot configuration for Maven

---

airsonic-main/src/main/resources/templates/top.html
contrib/airsonic.service

Issue430 merge latest upstream master

---

airsonic-main/src/main/java/org/airsonic/player/service/MediaFileService.java
airsonic-main/src/test/java/org/airsonic/player/service/MediaScannerServiceTestCase.java
airsonic-main/src/test/java/org/airsonic/player/util/MusicFolderTestData.java
airsonic-main/src/test/resources/MEDIAS/cueAndFlac/airsonic-test.cue

#447 fix broken cue indexing

---

airsonic-main/pom.xml
airsonic-main/src/main/java/org/airsonic/player/spring/LoggingExceptionResolver.java
pom.xml

#412 Add feature to handle nested client abort exceptions

---

airsonic-main/src/main/java/org/airsonic/player/controller/MusicFolderSettingsController.java
airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java

#473 change the log rule for expunge to show log

---

docs/README.md
docs/proxy/README.md
docs/proxy/apache.md

#482 Add reverse proxy configuration guide for Apache

---

docs/media/coverart.md

#254 add document for cover art

---

airsonic-main/pom.xml
airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
pom.xml

#497 fix star rest api

---

airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java
airsonic-main/src/main/java/org/airsonic/player/service/ArtistService.java
airsonic-main/src/test/java/org/airsonic/player/service/ArtistServiceTest.java

#505 Update artist image URLs with username parameter

---

README.md
airsonic-main/pom.xml
airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
airsonic-main/src/main/java/org/airsonic/player/util/StringUtil.java
airsonic-main/src/test/java/org/airsonic/player/util/StringUtilTestCase.java
pom.xml

#516 Support webp images for CoverArt

---

airsonic-main/src/main/resources/templates/head.html
airsonic-main/src/main/resources/templates/home.html
airsonic-main/src/main/resources/templates/homePager.html
airsonic-main/src/main/resources/templates/mediaMain.html
airsonic-main/src/main/resources/templates/playQueue.html
airsonic-main/src/main/resources/templates/podcastChannel.html
pom.xml

#541 fix code scanning alert

---

airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_nl.properties

Fixed missing dutch i18n for main.recentlyplayed

---

.github/ISSUE_TEMPLATE/release_preparation.yaml

#601 chore: Add Release Issue Template

---

.github/ISSUE_TEMPLATE/bug_report.yaml
airsonic-main/pom.xml
airsonic-sonos-api/pom.xml
install/docker/pom.xml
integration-test/pom.xml
pom.xml
subsonic-rest-api/pom.xml

#603 Bump up edge version to 11.1.5

---

airsonic-main/src/main/java/org/airsonic/player/service/PlaylistService.java

Fix #666 
This pull request includes changes to the `PlaylistService` class in `airsonic-main/src/main/java/org/airsonic/player/service/PlaylistService.java` to handle media files with no duration more gracefully. The most important changes include adding a new method to filter out files with no duration and updating existing methods to use this filter.
Enhancements to file handling:
* Added a new method `filterNoDurationFiles` to filter out media files with no duration and log a warning for each such file.
* Updated the `setFilesInPlaylist` method to use `filterNoDurationFiles`, ensuring that only files with a duration are processed and counted. [[1]](diffhunk://#diff-ccc0c78018553190f0df3756a7156e3e7c0ab20fe39c4d3567c04df0df15ba43R192-R202) …

#666 Add filtering for media files with no duration in PlaylistService

---

airsonic-main/src/main/java/org/airsonic/player/controller/UserSettingsController.java

fix: #734 update InitBinder annotation to specify the command
